Objetivo 0. Problema jeugo del rol
Morad02/F1Data pull request #1
Opened 2023-09-15 12:41 UTC by Morad02

Se ha editado usando VSCode

2023-09-16 07:56 UTC, JJ requested changes
Los ficheros con imágenes a los que apuntas no están en el PR. Por otro lado, no has formulado claramente el problema. Tarda mucho, ¿quieres que tarde menos?
También has marcado que tienes conocimiento personal del problema. Justifica que es así.

2023-09-16 08:56 UTC, Morad02 commented
Tras pensarlo detenidamente, creo que  no tengo los conocimientos suficientes sobre estos datos. Por ello, creo que voy a cambiar de problema.  Como no se ha incluido la carpeta doc, supongo que tendré que cerrar este pull request y hacer otro?

2023-09-16 13:40 UTC, Morad02 commented
@JJ  Tras pensarlo detenidamente, creo que no tengo los conocimientos suficientes sobre como procesar estos datos. Por ello, he cambiado de problema. Esta es la nueva lista de comprobación: 

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
       Sí, además de que me ha pasado más de una vez, creo que tengo los conocimientos sobre como operar con los 
      datos de las películas y como podría utilizarlos para resolver el problema (por ahora una idea vaga)
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
       Sí, ya que se necesita acceso desde cualquier parte y en cualquier momento al servicio
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
       Sí, además de guardar información sobre las películas habrá que utilizar los datos de estas para realizar buenas 
       recomendaciones al usuario
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`? 
       Sí, se han realizado dos capturas. Al final del Readme hay dos enlaces para acceder a ellas.
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
       Sí, se obtendrán los datos de las películas a través de una API o algún sitio web y luego se alojarán en la base de 
       datos
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-16 18:17 UTC, JJ commented
La lista de comprobación debería estar en el mismo sitio, en el cuerpo del PR.

2023-09-16 18:22 UTC, JJ requested changes
Estás describiendo dos problemas, no uno solo. Y el primero de ellos no es demasiado concreto. Recomendar películas, ¿en qué contexto? Los algoritmos de recomendación, por otro lado, rara vez son simples y los que son simples no tienen una lógica de negocio compleja (recomendar películas con el mismo director, o del mismo género).
Te aconsejaría que hicieras una vez más el juego, con alguna persona de tu confianza, o en todo caso rellenes la ficha y concretes *un* solo problema que puedas ir solucionando a lo largo de la asignatura.

2023-09-17 11:03 UTC, JJ commented
> Se ha editado usando VSCode @JJ
> 
>     * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Es verdad que nunca he presentado informes de gastos, pero si que tengo conocimientos básicos de
>       reconocimiento de texto en imágenes y procesamiento de imágenes que creo que serían el punto de partida para
>       resolver este problema
> 

Es esencial que tengáis conocimiento personal. Si has respondido que no, eso invalida el problema presentado.

Por otro lado, todo el código que uséis debéis programarlo vosotros. Si vais a usar alguna biblioteca de OCR, una vez más invalida el problema (que, por otro lado, tampoco está bien formulado, ya que por lo que comentas aquí se trata de hacer reconocimiento de imágenes sobre facturas)

2023-09-17 13:57 UTC, Morad02 commented
@JJ he planteado un nuevo problema donde he tenido en cuenta sus comentarios. 
Gracias y siento las molestias.

2023-09-18 05:31 UTC, JJ approved these changes
:+1:  No acabo de entender el problema, ni si se trata de sólo una materia prima, ni si es un problema de asignación de materias primas a fábricas, o de recorrido de las furgonetas o de vehículos para una carga determinada. Puede ser un problema insoluble por los muchos parámetros libres o tan simple como "usa tantas furgonetas como sean necesarias" Tendrás que concretar *mucho* más en el siguiente objetivo si se quiere intentar resolver de veras, o dividir el problema en diferentes partes y para eso necesitas realmente tener información personal.
Y por favor, cuida bien la ortografía y los errores de typeo. En VSCode puedes activar un plugin para que lo haga.

2023-09-18 05:31 UTC, JJ commented on README.md
> +Una empresa dispone de una flota de vehículos, donde cada vehículo se caracteriza por el consumo que tiene y la capacidad de almacenamiento. La actividad de esta empresa es la de reponer materia prim
Evita los typos, por favor.

2023-09-18 06:01 UTC, merged