[IV-23-24] Planificación del proyecto
Morad02/F1Data pull request #2
Opened 2023-09-21 14:19 UTC by Morad02

Usando el desarrollo ágil. Historias de usuario, milestones ...etc

**Milestones**
* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

**Historias de usuario**
* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-21 15:38 UTC, JJ requested changes
Trata de entender y aplicar el concepto de producto mínimamente viable, por favor.

En cuanto a "personas", si te sirve para establecer roles y diferente lógica de negocio, es útil. Ponerlo para llamar a los usuarios con diferente nombre tampoco aporta mucho.

2023-09-21 15:38 UTC, JJ commented on docs/historiasUsuario.md
> +[HU1] Ignacio está cansado de calcular el menor número de vehículos posible para transportar un pedido.
Como os dije en clase, esto tiene que ser una herramienta para poder empezar con la modelización del problema. Por eso tienes que añadir todo el contexto necesario para empezar a hacerlo, usando todos los detalles que provengan de tu conocimiento del tema.

2023-09-21 15:38 UTC, JJ commented on docs/historiasUsuario.md
> +[HU2] María cada vez le regaña más su jefe porque su almacén gasta mucho combustible para transportar pedidos.
Si los dos necesitan la misma lógica de negocio, serían uno solo.

2023-09-21 15:38 UTC, JJ commented on docs/milestones.md
> +[M0] Diseñar y implementar estructuras de datos para definir:
"Diseñar e implementar" son tareas, no productos. Como os he dicho en clase, el producto tiene que describirse como tal y también qué lo hace viable.

2023-09-21 17:13 UTC, Morad02 commented
@JJ  actualizado teniendo en cuenta sus consejos.

2023-09-21 18:05 UTC, JJ requested changes
Aunque la HU parece que describe todo lo necesario adecuadamente, sigues sin plasmar correctamente el concepto de producto mínimamente viable que tiene que ser cada milestone. Recuerda que tienen que ser productos de complejidad creciente.

2023-09-21 18:05 UTC, JJ commented on docs/milestones.md
> +[M0] Estructura de datos que permita la gestión de vehículos, materia prima, almacén y pedidos
Una estructura de datos no es un producto. Por favor, no repitáis los errores del año pasado. Mira los objetivos de la asignatura para ver exactamente qué es lo que habría que entregar.

2023-09-21 18:05 UTC, JJ commented on docs/milestones.md
> +[M1] Métodos para gestionar vehículos, materia prima, almacén y pedidos.
"Métodos" tampoco es un producto.

2023-09-21 19:57 UTC, Morad02 commented
@JJ milestones corregidos.  Tras hacerlo de esta forma pensado en el objetivo, entregable, viabilidad y soporte me han surgido estas dudas. Si el entregable de un milestone es un código fuente, hay que entregar pruebas que demuestren que ese código funciona ? Y en cuento al soporte, si el producto es un diseño, cuál sería el soporte? 

Gracias!

2023-09-22 05:23 UTC, JJ commented
> @JJ milestones corregidos. Tras hacerlo de esta forma pensado en el objetivo, entregable, viabilidad y soporte me han surgido estas dudas. Si el entregable de un milestone es un código fuente, hay que entregar pruebas que demuestren que ese código funciona ? Y en cuento al soporte, si el producto es un diseño, cuál sería el soporte?

Esas pruebas serían los tests, claro. Sin embargo, antes de escribir los tests también puede haber productos viables, en cuyo caso tendrías que explicar quién dice que lo son (puede ser una persona, o algún otro procedimiento)

2023-09-22 05:38 UTC, JJ requested changes
Una vez más, mirar los objetivos sucesivos puede darte una pista de qué pasos se suelen hacer en un proyecto. Pero piensa en las preguntas que te he hecho, que también.

2023-09-22 05:38 UTC, JJ commented on docs/milestones.md
> +[M0] **Diseño de la estructura de datos**
¿Para qué se define la estructura de datos? Si no dices qué hace esa estructura de datos viable, no constituiría una definición válida. 
En todo caso, estás poniendo el énfasis una vez más en la tarea, no en la razón por la que se hace la tarea.

2023-09-22 05:38 UTC, JJ commented on docs/milestones.md
> +- *Viabilidad:* Establece la base del sistema. Sin esta estructura, no se podría desarrollar las funcionalidades pedidas.
La establece, ¿en base a qué?

2023-09-22 11:28 UTC, Morad02 commented
@JJ historias de usuarios y milestones corregidos.

2023-09-22 17:42 UTC, JJ approved these changes
:+1: Es posible que se queden un poco cortas las historias de usuario; quizás sería conveniente que le añadieras un poco más de contexto. En todo caso lo vas a necesitar para el objetivo siguiente.

2023-09-22 18:03 UTC, merged