[IV-23-23] Objetivo7
Morad02/F1Data pull request #62
Opened 2023-12-03 18:04 UTC by Morad02

* [x] ¿Se han registrado todos los eventos relevantes en la aplicación, es decir, se
  han añadido comandos para registrarlos en todos ellos?
  - Sí, los relativos a la lógica de negocio
* [x] ¿Se han seguido buenas prácticas en el uso de configuración remota?
* [x] ¿Se han explicado correctamente las decisiones técnicas que se han tomado
  sobre las bibliotecas usadas?
  - Sí, en la carpeta docs
* [x] ¿Te has asegurado de que el fichero `.env` no se pueda añadir
accidentalente al repositorio?
  - Sí, usando el .gitignore
* [x] ¿Los logs y la configuración están en un objeto que se *inyecta* en las
clases manejadoras para su uso?
  - Sí
* [x] ¿*Realmente* se usan los logs en las diferentes clases en eventos
importantes?
* [x] ¿Se testea el código creado para logs y configuración, igual que
    cualquier otro código?
  - Sí
* [x] ¿La clase o módulo de configuración lee *siempre* las variables de entorno? 
  - Sí, usando dotenv

2023-12-17 09:48 UTC, Morad02 commented
@danieeeld2 @pluque01 listo para revisión.

2023-12-17 11:35 UTC, danieeeld2 approved these changes
:+1: Muy buen trabajo en general. Me ha parecido especialmente curioso que montes la configuración desde 0, pero veo que,  por lo que has escrito , no había muchas opciones. Personalmente, añadiría un test para la configuración, nada muy complicado, por ejemplo, en el mio tengo:
```go
package internal

import (
	"testing"
)

func TestConfiguracion(t *testing.T) {
	tempConfigFile := "../test_config.yaml"

	config, err := loadConfig(tempConfigFile)
	if err != nil {
		t.Fatalf("Error loading config: %v", err)
	}

	if config == nil {
		t.Error("Expected non-nil config, got nil")
	}
}
```
Por lo demás lo veo todo genial. Muy buen trabajo 😄

2023-12-17 11:35 UTC, danieeeld2 commented on docs/eleccion_logger.md
> +# Configuration management
Tienes esto repetido esto aquí cuando lo tienes en configManag.md

2023-12-17 11:35 UTC, danieeeld2 commented on test/gestor_vehiculos_test.ts
> +describe("Logger - Asignación de Pedidos", () => {
Buena forma de usar los` logs` para testar el código 😄

2023-12-17 11:35 UTC, danieeeld2 commented on utilities/config_ma.ts
> +export class ConfigMa {
😯

2023-12-17 13:59 UTC, Morad02 commented
@danieeeld2 te agradezco por tu revisión y los consejos que me has proporcionado, sobre todo en esta época tan apretada. Espero no haberte hecho perder mucho tiempo.  Muchas gracias y espero que todo te vaya bien.

2023-12-17 14:02 UTC, Morad02 commented on docs/eleccion_logger.md
> +# Configuration management
Resuelto en 24b407784b2b46b8e4c0c8fca42e4f4d8c5965bd

2023-12-17 14:18 UTC, danieeeld2 commented
> @danieeeld2 te agradezco por tu revisión y los consejos que me has proporcionado, sobre todo en esta época tan apretada. Espero no haberte hecho perder mucho tiempo. Muchas gracias y espero que todo te vaya bien.

La verdad que va justillo de tiempo la cosa jajaja, pero como eras tú, que siempre entregaba primero y le tocaba revisar al resto, he dicho voy a sacarle unos minutillos para revisarle😂

2023-12-17 14:52 UTC, Morad02 commented
@JJ Listo para revisión.

2023-12-17 14:57 UTC, pluque01 approved these changes
Yo lo veo muy bien. Por decir algo te he comentado sobre los mensajes de log. Por lo demás, te doy mi visto bueno. 👍

2023-12-17 14:57 UTC, pluque01 commented on utilities/config_ma.ts
> +    getLogerConfig(): Map<string, string>
typo en `getLogerConfig`

2023-12-17 14:57 UTC, pluque01 commented on src/gestor_vehiculos.ts
> +            logger.info(`Pedido asignado correctamente`);
Aquí igual podrías loggear también algún identificador sobre el pedido.

2023-12-17 14:57 UTC, pluque01 commented on src/gestor_vehiculos.ts
> +            logger.info(`Pedido no asignado`);
Lo mismo que aquí.

2023-12-17 15:20 UTC, Morad02 commented on utilities/config_ma.ts
> +    getLogerConfig(): Map<string, string>
Resuelto en ebf436d3ab1ce61d2bb0edb9bb0a33164efcdeb5

2023-12-20 07:10 UTC, JJ requested changes
Muchas gracias a @danieeeld2 y @pluque01 por su revisión; el problema principal es la ausencia del fichero de configuración y el uso de uno que no sigue las buenas prácticas. El resto, en el mismo comentario.

2023-12-20 07:10 UTC, JJ commented on iv.yaml
> +  - .env
ESte fichero debe estar presente en el repo. No está en este PR. Por otro lado, *este* fichero es el que no puedes añadir al repo nunca. Si quieres usar configuracion con dot.env usa otro fichero, preferiblemente uno cuyo nombre deje claro que no es el real.

2023-12-20 07:10 UTC, JJ commented on src/gestor_vehiculos.ts
> +            logger.info(`Pedido asignado correctamente`);
Por favor, tened en cuenta todos los comentarios que se os hayan hecho. En general, el objetivo del log es la observabilidad; si no está claro qué es lo que se está observando, pierden su utilidad.

2023-12-20 10:36 UTC, Morad02 commented on src/gestor_vehiculos.ts
> +            logger.info(`Pedido asignado correctamente`);
resuelto en 56c7a363c1177dfb0e622c6c6843f22ff641d5bb

2023-12-20 10:37 UTC, Morad02 commented on src/gestor_vehiculos.ts
> +            logger.info(`Pedido no asignado`);
56c7a363c1177dfb0e622c6c6843f22ff641d5bb

2023-12-20 10:38 UTC, Morad02 commented on iv.yaml
> +  - .env
Resuelto en ce7436bda6fae9bd7a298e107edae7be2973509f

2023-12-20 10:46 UTC, Morad02 commented
@JJ siento mucho que se me haya pasado  el comentario de mi compañero.  Ya están realizados los cambios pedidos. Listo para revisón!

2023-12-20 10:56 UTC, JJ approved these changes
Y si puedes DRYar antes del siguiente, mejor... Porque habrá un siguiente, ¿no? :eyes:

2023-12-20 10:56 UTC, JJ commented on test/gestor_vehiculos_test.ts
> +    it("Número de logs", () => {
Un poco de DRY, porfa...

2023-12-20 11:17 UTC, Morad02 commented on test/gestor_vehiculos_test.ts
> +    it("Número de logs", () => {
Resuelto en 441a7cfb3b0003791180909c11661b79909484ee. Claro, aquí se llega hasta el final :grin:

2023-12-22 11:51 UTC, merged